FROM alpine:3.22

RUN set -eux; \
    apk --no-cache add \
        mpd=0.24.7\
&& mkdir -p /usr/local/mpd/ 

COPY mpd.conf /usr/local/mpd/mpd.conf \
&& apk del mpddep \
&& rm -rf /var/cache/apk/* /tmp/*
