FROM alpine:3

ARG VERSION

RUN set -ex && \
    apk add --no-cache mpd \
&& mkdir -p /usr/local/mpd/ \
&& sed	-e 's:\#user.*:user\t\t"mpd":' \
  -e 's:\#log_file.*:log_file\t\t"syslog":' \
  doc/mpdconf.example > /usr/local/mpd/mpd.conf \
&& apk del mpddep \
&& rm -rf /var/cache/apk/* /tmp/*
