FROM shinsenter/phpfpm-apache:dev-php7.4

WORKDIR /var/www/html
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    libzip-dev \
    libwebp-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget -O maccms10.zip https://github.com/clyde3/maccms10Ultra/archive/refs/heads/main.zip.zip \
    && unzip maccms10.zip \
    && mv maccms10-main/* . \
    && mv maccms10-main/.* . 2>/dev/null || true \
    && rm -rf maccms10-main maccms10.zip
    

RUN chmod -R 755 /var/www/html \
    && chown -R www-data:www-data /var/www/html

RUN mkdir -p /var/www/html/datas \
    && chmod -R 777 /var/www/html/datas

EXPOSE 80

CMD ["php-fpm"]
