services:
    maccms:
        image: esme518/docker-maccms10
        container_name: maccms
        restart: always
        volumes:
            - /www/data:/var/www/html
        ports:
            - 3600:80
    maccms-db:
        image: yobasystems/alpine-mariadb:latest
        container_name: maccms-db
        restart: always
        volumes:
            - /www/mysql:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD=123456
