FROM shinsenter/phpfpm-apache:dev-php7.4

COPY docker-entrypoint.sh /entrypoint.sh

ENV REPO_URL https://github.com/magicblack/maccms10.git
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN set -ex \
    && mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \
    && a2enmod remoteip \
    && sed -i 's/%h/%a/g' /etc/apache2/apache2.conf \
    && echo "ServerName localhost" >> /etc/apache2/apache2.conf

COPY <<EOT /etc/apache2/mods-enabled/remoteip.conf
RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy 127.0.0.0/8
RemoteIPTrustedProxy ::1/128
EOT

VOLUME /var/www/html

RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

ENV ADMIN_PHP cmsadmin.php

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
